name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pyinstaller

    - name: Create placeholder files
      run: |
        echo "<html><body><h1>Placeholder</h1></body></html>" > placeholder.html
        echo "{}" > placeholder.json

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name GravyJobs gravy_jobs_gui.py --hidden-import tkinter --hidden-import tkinter.ttk --hidden-import tkinter.scrolledtext --hidden-import tkinter.messagebox

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: GravyJobs-Windows
        path: dist/GravyJobs.exe